### ISSUE TITLE
Large numbers erroneously rounded in editor

### ISSUE THREAD

**Issue by manivannan-r** [josdejong/jsoneditor#451] opened 2017-08-22 08:14 UTC
![screen shot 2017-08-22 at 2 10 56 pm](https://user-images.githubusercontent.com/17785551/29556562-d73ab4b2-8743-11e7-9376-065ad3c32ac6.png)

**From** 

```
{
  "VALUE": 3754572000000010017
}

```
**To** 

```
{
  "VALUE": 3754572000000010000
 }

```
**FYI :** JavaScript can only handle exact whole numbers up to about 9000 million million (that's 9 with 15 zeros). Higher than that and you get garbage. 

Please provide a workaround for this. @josdejong 

thanks

**Comment by josdejong** [comment] 2017-08-22 17:58
This is a duplicate of #231, please check out the discussion over there.

**Closed** 2019-06-12 19:50 UTC
Labels: duplicate
