### ISSUE TITLE
Hidden (clipped) context menu

### ISSUE THREAD

**Issue by nnseva** [josdejong/jsoneditor#416] opened 2017-06-22 17:41 UTC
When the editor div is placed inside another one, the context menu appears hidden/clipped by the outer div.
This happens only in version 5 of the editor. Version 4 works properly.

[version 5 example](https://jsfiddle.net/5m1dusu8/14/) vs [version 4 example](https://jsfiddle.net/vokcw62v/2/)

**Comment by josdejong** [comment] 2017-06-22 18:07
Thanks for bringing this up. 

The issue with the correctly working version 4 is that it didn't work correctly when used inside for example bootstrap modals and that sort of situations (see also #104). Therefore I went "back to the basics" with a simple inline div instead of an absolutely positioned one. I think it is a bit of an edge case: if you create the editor this small it's not really usable anyway, or is it?

**Comment by nnseva** [comment] 2017-06-22 18:30
Really I am using your JSON editor in the Django application to edit a field of the record, see [there](https://github.com/nnseva/django-jsoneditor). Having multiple editing fields on one page we need to have a JSON editor window as small as possible.

I would suggest you create some customization feature allowing to choose where the context menu should be created - either inline or absolute.

**Comment by josdejong** [comment] 2017-06-23 08:15
> Really I am using your JSON editor in the Django application to edit a field of the record, see there. Having multiple editing fields on one page we need to have a JSON editor window as small as possible.

I understand, thanks for explaining.

> I would suggest you create some customization feature allowing to choose where the context menu should be created - either inline or absolute.

Ideally, the context menu should "just work" and be absolutely positioned instead of inline. It will require some effort though to get that right in all circumstances, but should be solvable. Probably attach to the container of the JSONEditor instead of the document body to maintain encapsulation. Customizing it could be an option but that's just moving the problem to the user, I would rather like to solve it for real. 

I don't expect to find time to solve this short term, help would be welcome.

**Comment by dvarrazzo** [comment] 2017-10-26 15:11
Could you implement an `onMenu()` callback to call when `ContextMenu` is displayed to allow users in the corner case of a small editor to customize how the menu is displayed?

**Comment by dvarrazzo** [comment] 2017-10-26 15:18
Note: see [this comment](https://github.com/nnseva/django-jsoneditor/issues/29#issuecomment-339699269) for an example of the customisation that can be made in an app using the the menu to fix the problem.

**Comment by chaud** [comment] 2019-03-27 22:42
We've fixed this in our application (which has no modals) with an `overflow: visible` on `div.jsoneditor-tree`:  ([Example](https://jsfiddle.net/hq1xvLo4/))

Granted, this isn't a fix for special cases, but I came across this and #368 when looking for a solution and wanted to add a workaround for some cases.

**Comment by josdejong** [comment] 2019-03-28 18:55
I think we can close this issue, since some time we're back to using an absolutely positioned menu which overflows the editor, it should work out of the box with the latest version of jsoneditor.

**Comment by chaud** [comment] 2019-03-28 19:34
It currently [does work out of the box](https://jsfiddle.net/yb7zpgs1/), **unless** clicking on an [empty object](https://jsfiddle.net/yb7zpgs1/1/). Clicking on the anchor to open the actions menu next to "(empty object)" results in a clipped menu. The same goes for the [empty array](https://jsfiddle.net/yb7zpgs1/2/) line in this example.

**Comment by josdejong** [comment] 2019-03-28 19:39
ah, good find! That is a bug and should be fixed. I will reopen this issue.

**Comment by josdejong** [comment] 2019-03-30 20:00
Fixed via 9e3b6fb19655d21e259666221cb97b36fa99ce99 (not yet published)

**Comment by nnseva** [comment] 2019-04-01 06:41
The wondefull news! Don't miss to remove `padding-bottom: 300px` from `div.jsoneditor-tree div.jsoneditor-tree-inner` workaround.

**Comment by josdejong** [comment] 2019-04-02 18:48
Good point @nnseva , that's totally redundant now :D

**Closed** 2019-04-03 13:08 UTC
Labels: bug, help wanted

**Comment by josdejong** [comment] 2019-04-03 13:10
This should be fixed now in `v5.32.2`

**Comment by ozcanyarimdunya** [comment] 2019-06-13 22:25
I am using `v5.32.5` but i came across with same problem. :(

**Comment by josdejong** [comment] 2019-06-15 12:15
How to reproduce your issue @ozcanyarimdunya ?

To be sure, I created a jsbin with the latest version 6.0.0 (shouldn't differ from 5.32.5 in this regard):
 
https://jsbin.com/rujegux/edit?html,output
