### ISSUE TITLE
Input field with multiple values from autocomplete

### ISSUE THREAD

**Issue by developer-anilpatidar** [josdejong/jsoneditor#1039] opened 2020-07-08 05:54 UTC
is it possible to add multiple value in string type field with autocomplete
like:
column_list: "id;name;email"

I never want to use array type of filed just want to continually add multiple value in a single filed with autocomplete
when start typing id show autocomplete then add ";" then again start typing in the same field such as "name" then  autocomplete suggestion will show.

**Comment by josdejong** [comment] 2020-07-08 19:27
I think that should be possible, the autocomplete function is quite flexible and customizable: with `filter` and `trigger` you can control what to match and when to trigger, see docs on `autocomplete` (and there are a couple of examples in the /examples folder).

https://github.com/josdejong/jsoneditor/blob/develop/docs/api.md

**Comment by developer-anilpatidar** [comment] 2020-07-12 13:22
Perfect, It's working!!
Thanks @josdejong

**Comment by josdejong** [comment] 2020-07-12 13:45
Awesome! Thanks for reporting back. I'll close this issue now.

**Closed by josdejong** 2020-07-12 13:45 UTC
Labels: question

**Comment by cpopolo** [comment] 2023-01-23 17:36
@josdejong this is a life-saver, thank you...  But I am having trouble trying to implement a pick-list method for restricting a node to a limited set of choices.  E.g. for a node called 'fruit', how can I limit the autocomplete to only allow ['apple','peach','mango']?  Ideally, the editor would allow me to show a <select>, and even more ideal, the <select> would allow 'multiple' choices.

**Comment by josdejong** [comment] 2023-01-24 09:00
@cpopolo you can maybe use a JSON Schema, which can provide an enum dropdown for a limited list of inputs, and shows a warning icon when the value is invalid. See the "gender" dropdown in https://github.com/josdejong/jsoneditor/blob/develop/examples/07_json_schema_validation.html.

**Comment by cpopolo** [comment] 2023-01-24 19:20
Thanks Jos, this is working nicely.  I'm now deep into the rabbit hole of the 'schema' option which I knew I would need to get to at some point...  A quick follow-up question if you can:  I've read through the[ issue #57](https://github.com/json-schema-org/json-schema-spec/issues/57) about named enumerations and cannot seem to tell if that has been resolved.  Is there an accepted way to show a list of enumerated options along with a brief description for each?  There are certain fields in my structure that require a short code, but it would be far more helpful if the end-user could see a fuller description.  This is an example where I have left it for now:

`                    "properties": {
                        'iso': {"type" : "string", "enum": ['isone','isony','pjm','miso','spp','ercot','caiso','ieso']},
                        'ba': {
                            "type": "string", 
                            "oneOf": [
                                {"const": "isone_nh", "description": "ISONE NH"},
                                {"const": "isone_nema", "description": "ISONE North MA"},
...this list could be 100+ elements long...
                            ]
                        },
`

**Comment by josdejong** [comment] 2023-01-24 19:51
In JSONEditor, you cannot use `oneOf` to render an enum with a description or so, it's really just looking at `enum`. I don't think there is a way to show a description for individual enum values, though you can put a description in the parent of the enum, and then hover the key (fieldname) in JSONEditor to see the description, i.e.

```
"properties": {
   'iso': {
    "type" : "string", "enum": ['isone','isony','pjm','miso','spp','ercot','caiso','ieso'],
    "description": "Choose one of bla bla bla"
   },
```

**Comment by cpopolo** [comment] 2023-01-24 20:32
I see...  The problem is that the "ba" list of options in my example can be quite long. I wonder if it's possible to build a render callback that would make the "enum" behave more like a <select> element in HTML; where the option values are stored into the JSON, but the user sees a more useful list of descriptions.  E.g., <option value='isone_nh'>ISO New England NH</option>...  The JSON value would be set to "isone_nh" but the user selected "ISO New England NH" from the dropdown list.  Perhaps an experiment for another day - you've been more than enough help already!

**Comment by josdejong** [comment] 2023-01-25 07:57
Yeah I understand.

The successor of this library, [`svelte-jsoneditor`](https://github.com/josdejong/svelte-jsoneditor), allows writing your own component to render a value (depending on the conditions). There is an [example here](https://github.com/josdejong/svelte-jsoneditor/blob/main/src/routes/examples/custom_value_renderer/%2Bpage.svelte) on how to render a `ReadonlyPassword` and use the built-in `EnumValue` component to render a dropdown (without needing JSON schema). You can just as easily create your own enum component with dynamic description (maybe with an info icon on the right side or so).
