### ISSUE TITLE
Fire event when JSON edit is complete?

### ISSUE THREAD

**Issue by srinivasrk** [josdejong/jsoneditor#715] opened 2019-06-11 16:30 UTC
Is there a way to know when user has finished editing a key / value? I see that there is onChange callbacks that trigger for each character changed, but not for the whole value change

**Comment by josdejong** [comment] 2019-06-11 18:11
Is this a duplicate of #649?

**Comment by srinivasrk** [comment] 2019-06-11 18:13
@josdejong ! My mistake it is a duplicate. I'll go ahead and close this issue

**Comment by josdejong** [comment] 2019-06-11 18:20
:+1:

**Closed by josdejong** 2019-06-11 18:20 UTC
