### ISSUE TITLE
When input Korean use IE 11, contents will repeat.

### ISSUE THREAD

**Issue by Rem486** [josdejong/jsoneditor#801] opened 2019-09-24 01:16 UTC
Hi, i had met with some difficulties.

When i use ` JSON Editor Online ` to input `Korean` in `IE 11` .The content will repeat.

The code mode :

![json-editor](https://user-images.githubusercontent.com/22462424/65415991-71748d80-de29-11e9-8250-533f0d700288.gif)

The tree mode is ok:

![json-editor-2](https://user-images.githubusercontent.com/22462424/65416465-78e86680-de2a-11e9-819f-3ae519aa48e9.gif)

>Only in IE 11 have this problem,the other brower is normal.

![1569287726](https://user-images.githubusercontent.com/22462424/65473811-e7b9d400-deab-11e9-9284-e3f37549732d.png)

plz help me with this. Thank you very much!

**Comment by josdejong** [comment] 2019-09-29 14:34
Thanks for reporting @Rem486 . Looks like an issue in the Ace editor. It sounds the same as this issue: #253. Unfortunately I don't know how I can reproduce it or do something about it. It could be that it is a known issue of Ace editor.

Only search result that I found that could be relevant is this (old) one: https://support.microsoft.com/en-ca/help/3203974/korean-or-japanese-ime-composition-may-not-work-correctly-in-internet

**Comment by Rem486** [comment] 2019-09-30 01:40
Thanks for your reply @josdejong ! 
Yep,this seems to be a issue with the ACE editor. I found a `pr` ([Fixed Windows OS / IE unicode IME not working](https://github.com/ajaxorg/ace/pull/3463)) to fixed it. But the dependencies of [brace](https://github.com/thlorenz/brace) seems to stop updating ACE version, so the problem has not been fixed. 

Finally, I added the code in the `brace` ,then build the `jsoneditor.js` to resolve this problem.😂😂

**Comment by josdejong** [comment] 2019-09-30 17:56
Ahh, I see now that `brace` is behind, it uses Ace v1.2.9 (released 2 years ago), the latest version is 1.4.6 (less than a month ago). Thanks for figuring this out @Rem486.

I will have a look into this, see if we can do anything about brace or find another way to be able to use the latest version of Ace.

**Comment by josdejong** [comment] 2019-10-13 07:18
@Rem486 I've just published `jsoneditor@7.1.0` containing the latest version of Ace editor (`1.4.6`). Can you give this a try and see if it fixes the Korean input issues?

**Comment by Rem486** [comment] 2019-10-21 05:53
@josdejong Thanks a lot！
I've already verified this issue in the `IE11` use `jsoneditor@7.1.0`,  it's ok! 🎉 

But,there still had a small issue for ` Ace editor@1.4.6` 😃 https://github.com/ajaxorg/ace/issues/4080 .

If you have time, we can update to `Ace editor@1.4.7`. https://github.com/ajaxorg/ace-builds/commit/5ad04a46e8e0981a65dd982693e5d19a2209311c

**Comment by Rem486** [comment] 2019-10-22 06:42
There's already had a pr from the github application~

https://github.com/josdejong/jsoneditor/pull/820

**Comment by josdejong** [comment] 2019-10-22 18:05
Yes, I hope to do a release tomorrow.

**Comment by josdejong** [comment] 2019-10-22 18:06
Good to hear it fixes the issues with Korean inputs!

**Comment by josdejong** [comment] 2019-10-23 12:32
Fixed now in `v7.2.0`, which uses Ace edtior `v1.4.7`. I've also changed the version numbers of the dependencies to inexact version numbers: `^1.4.7`, so you can control this yourself.

**Closed by josdejong** 2019-10-23 12:32 UTC

**Comment by Rem486** [comment] 2019-10-24 01:46
Thanks a lot ! 🎉
