### ISSUE TITLE
How can I programatically reset all the active searches and highlights?

### ISSUE THREAD

**Issue by hi-files** [josdejong/jsoneditor#1552] opened 2023-09-18 15:21 UTC
I added some custom logic to highlight some searches and I am using a foreach on the searched nodes, and for all the discovered nodes I am using:

node.expanded = true;
node.fieldSearch = true;
node.fieldSearchActive = true;

The problem in my case is that after I clear the selection or after I make a new selection, the old highlights remain active. 
I am using a foreach to reset all the previous highlighted options, but it seems that setting everything to false doesn't help.

It seems that there is a cache/variable that stores all the previous highlights and when I clear the search or make a new search, all of the previous search options are highlighted again.

The question is, how can I clear all the highlights programatically? Or how can I reset all previous search data when I make a new search?

My entire issue is related to: fieldSearch and fieldSearchActive, which somehow is remembered when a new search is being done.

**Comment by hi-files** [comment] 2023-09-18 15:23
I can remove all classes that highlight active search options using JS, but this is not ok, since the jsoneditor is keeping somwhere all the fieldSearch and fieldSearchActive entries. I need to reset these details without reloading the page.

**Comment by josdejong** [comment] 2023-09-20 09:06
I think this is a duplicate of #1546

**Closed** 2023-09-20 09:07 UTC
Labels: duplicate
