### ISSUE TITLE
Could not find a declaration file

### ISSUE THREAD

**Issue by rahulkumarsingh73690** [josdejong/jsoneditor#1423] opened 2022-02-24 12:57 UTC
Could not find a declaration file for module 'jsoneditor'. '/node_modules/jsoneditor/dist/jsoneditor.min.js' implicitly has an 'any' type.

**Comment by josdejong** [comment] 2022-03-01 08:43
I suppose you're asking about TypeScript support. See #22

Will close this issue as a duplicate of #22

**Closed by josdejong** 2022-03-01 08:43 UTC
