### ISSUE TITLE
Wrong by convert max value of long in C#

### ISSUE THREAD

**Issue by hedbisker** [josdejong/jsoneditor#577] opened 2018-09-06 05:45 UTC
I try to convert max value of long in C#
and I got after the convert a bigger number then long (in C#)

![image](https://user-images.githubusercontent.com/5356674/45137346-e63e4080-b1b0-11e8-971f-e56d95197eb3.png)

**Comment by hedbisker** [comment] 2018-09-06 08:16
Its look like a bug... it changes the value of the variable...

**Comment by josdejong** [comment] 2018-09-06 17:53
Thanks for reporting. 

This is a duplicate of #231, let's continue any discussion there.

**Closed by josdejong** 2018-09-06 17:53 UTC
