### ISSUE TITLE
Sort function improvement required

### ISSUE THREAD

**Issue by DariuszKa** [josdejong/jsoneditor#441] opened 2017-07-19 14:25 UTC
I need to compare and find differences in two attached json files.
To do so sorting is really crucial. Problem with all comparers available (not only http://jsoneditoronline.org/ but also http://json-diff.com/ or http://novicelab.org/jsonabc/) is that sorting or ignoring order works only for some depth properly.
[jsons.zip](https://github.com/josdejong/jsoneditor/files/1159385/jsons.zip)

**Comment by josdejong** [comment] 2017-07-21 09:27
Thanks for your suggestion, I will mark this as a duplicate of #143, let's continue the discussion there ok?

**Closed by josdejong** 2017-07-21 09:27 UTC
