### ISSUE TITLE
separator not working on safari

### ISSUE THREAD

**Issue by zhen-easytag** [josdejong/jsoneditor#915] opened 2020-02-26 15:49 UTC
The three dots separator in the middle is not working to resize the columns.

**Comment by josdejong** [comment] 2020-02-26 16:30
Thanks for reporting. I tested on Safari 13 and 12.1, the splitter seems to work but doesn't allow to smoothly move very far to the left or right. Is that what you also see? What version of Safari are you running?

**Comment by josdejong** [comment] 2020-02-26 21:19
@zhen-easytag can you try out if the issue is fixed in the latest version (`v5.2.4`)?

**Comment by zhen-easytag** [comment] 2020-03-02 17:07
that's fixed. Thanks.

**Comment by josdejong** [comment] 2020-03-02 17:21
👍 thanks for checking

**Closed by josdejong** 2020-03-02 17:21 UTC
Labels: bug, webapp
