### ISSUE TITLE
Issue regarding HTML entities

### ISSUE THREAD

**Issue by Xesau** [josdejong/jsoneditor#227] opened 2015-09-27 14:30 UTC
When you load in data containing escaped HTML entities (like `&amp;`) using `editor.set(JSON.parse(...))`, it doesn't parse the escaped entities into normal text (so in the field, the `&amp;` stays that and doesn't become `&`)
![Image 1](http://i.imgur.com/N4M54rP.png)

Once you focus the value, and then unfocus it, it does unescape them in the tree view, and in the output JSON, it doesn't get escaped again.
![Image 2](http://i.imgur.com/XdLf8ft.png)

But if you leave it untouched, and you save it, however, the entities get escaped doubly
![Image 3](http://i.imgur.com/181lXn2.png)

This inconsistency can result in, when you save and load again a few times, quadruply escaped entities:
![Image 4](http://i.imgur.com/CkD4swP.png)

A solution to this would be unescaping all the values when `editor.set` is triggered.

**Comment by josdejong** [comment] 2015-09-30 20:05
Thanks for bringing this up, the editor should just leave the text as is, and not render html codes like `&lt;` as `<`.

**Comment by josdejong** [comment] 2015-12-24 19:21
This is now fixed in the `develop` branch.

**Comment by josdejong** [comment] 2015-12-24 19:24
This is duplicate of #93 .

**Closed by josdejong** 2015-12-24 19:24 UTC
Labels: bug, duplicate
