### ISSUE TITLE
How to add 2 button tree and code to main menu bar

### ISSUE THREAD

**Issue by vu-cv** [josdejong/jsoneditor#1219] opened 2021-01-15 04:37 UTC
![2b](https://user-images.githubusercontent.com/30167935/104681953-23725000-5726-11eb-998f-02973480db9c.png)

**Comment by josdejong** [comment] 2021-01-15 19:34
This is a duplicate of #983, please continue any discussion there.

**Closed by josdejong** 2021-01-15 19:34 UTC
