### ISSUE TITLE
Long integer values garbled

### ISSUE THREAD

**Issue by BubaVV** [josdejong/jsoneditor#340] opened 2016-11-24 17:01 UTC
64-bit integers lose accuracy during parsing. Numbers longer 17 digits are rounded to 17 meaningful digits, it correspond to about 57 bits. To reproduce try to parse this example:

{"int":1234567890123456789,"str":"1234567890123456789"}

**Comment by josdejong** [comment] 2016-11-25 08:00
This is a duplicate of #231, let's continue any discussion there.

**Closed by josdejong** 2016-11-25 08:00 UTC
Labels: duplicate
