### ISSUE TITLE
 Possibility to add custom functionality in the main menu

### ISSUE THREAD

**Issue by luizsantoszup** [josdejong/jsoneditor#1032] opened 2020-07-03 20:17 UTC
Friends, something like the `onCreateMenu` method is possible, but something related to the` mainMenuBar`.

Add extra functionality in the main menu? Is there such a thing already?

**Comment by josdejong** [comment] 2020-07-04 08:06
Thanks for your input Luiz, I think this is a duplicate of #831, so I will close this issue in favor of the existing one.

**Closed by josdejong** 2020-07-04 08:06 UTC
Labels: duplicate
