### ISSUE TITLE
Unable to save

### ISSUE THREAD

**Issue by landylokesh** [josdejong/jsoneditor#179] opened 2015-04-13 09:33 UTC
Am unable to save the data.

**Comment by josdejong** [comment] 2015-04-13 10:07
Thanks for your report. Do you try to save a document online or to disk?

A common problem is that the file is too large, exceeding the limits. Can that be the problem?

**Comment by landylokesh** [comment] 2015-04-16 13:05
Am trying to save in online. i don't think its that much heavy

Thanks & regards,
Lokesh(LaNdY),
Chennai

**Comment by rohitw-daffodil** [comment] 2015-07-10 11:31
I am also facing the same issue, unable to save a 4 line code online for share with other.
Its wonderful if its working for us.

**Comment by josdejong** [comment] 2015-07-10 11:47
Do you get an error message, or see errors in the console output of your browser (open with F12 or Ctrl+Shift+J)?

**Comment by rohitw-daffodil** [comment] 2015-07-10 11:56
This is an screen shot of it:
![screenshot from 2015-07-10 17 22 40](https://cloud.githubusercontent.com/assets/12936101/8618121/b29ffbbc-2728-11e5-9595-c7d432412e21.png)

**Comment by josdejong** [comment] 2015-07-10 12:05
Thanks, this is helpful. So it's a CORS related issue. 

I think it's caused by the SSL version of the webapp not accepting the backend (you have opened `https://`).  You can try whether it works fine on http://jsoneditoronline.org/.

Let's see how we can solve this issue (and in the worst case, redirect to the `http` url instead)

**Comment by josdejong** [comment] 2015-07-10 15:39
For now the webapp redirects https://jsoneditoronline.org to http://jsoneditoronline.org (version 3.4.2, bottom center). You may need to refresh the page one or two times before you have the latest version.

To really solve the issue I will have to buy a certificate for the backend (instead of the current self signed one), or move the frontend and backend to the same domain. I will have a look into that.

**Comment by rohitw-daffodil** [comment] 2015-07-10 23:48
OK thanks. it's works and also thanks for this great tool.

**Comment by josdejong** [comment] 2015-07-11 10:49
Ok great! Thanks for letting me know.

I will close this issue now, assuming the reports of others had this same cause, and work on solving the `https` for real (instead of redirecting to `http`).

**Closed by josdejong** 2015-07-11 10:49 UTC
