### ISSUE TITLE
Uncaught SyntaxError: Unexpected token '<'

### ISSUE THREAD

**Issue by lmichratsimbazafy** [josdejong/jsoneditor#900] opened 2020-02-13 10:52 UTC
JsonEditor generate 'Uncaught SyntaxError: Unexpected token '<'' error when it is in code mode

**Comment by josdejong** [comment] 2020-02-13 19:09
Thanks for reporting @lmichratsimbazafy . How can I reproduce this issue?

**Comment by lmichratsimbazafy** [comment] 2020-02-14 06:51
thank  you @**josdejong**  for answering so quickly! I integrated the package into an existing project and I reproduced the example code like in react-advanced-demo, it works perfectly except only in 'code' mode which generates this error. Obviously, it is not blocking at all but it doesn't only highlight  the syntax.note : I just did `npm install jsoneditor` to install it and copied the link and script into index.html, may be the are more details that I haven't done yet.

**Comment by josdejong** [comment] 2020-02-15 10:02
Sorry I still don't know how to reproduce this. I've started the `react_advanced_demo` and switched to `code` mode but no such error. Is it possible to create a minimalistic example demonstrating the issue? In a jsbin or codesandbox or so?

**Comment by lmichratsimbazafy** [comment] 2020-03-08 21:43
Hi @josdejong,
Sorry for replaying so late ... in fact, it is not really an Json format error but it seems that the ace editor can't load properly the syntax highlighter for json mode so my tools take it as a JSON error. As I said, it is not blocking at all except that the syntax is not highlighted, it falls back to text mode

**Comment by josdejong** [comment] 2020-03-09 18:43
Thanks for getting back. What is your proposal? Without information on how to reproduce I can't do anything. Is there a simple way to reproduce this issue? Or would you like to close this issue?

**Comment by skeezus** [comment] 2020-07-16 01:28
I'm going to guess you ran `npm install jsoneditor` and linked the jsoneditor script in your html. You need one or the other, not both.

**Comment by skeezus** [comment] 2020-07-16 01:35
I also logged this in my console when I had this tag in my index.html <script src="jsoneditor/dist/jsoneditor.min.js"></script>

I later installed the package using npm, removed the script and everything worked fine.

**Comment by josdejong** [comment] 2020-07-18 09:11
Thanks for your feedback Braden.

I'll close this issue now due to to lack of information.

**Closed by josdejong** 2020-07-18 09:11 UTC

**Comment by cyrojyro** [comment] 2021-04-06 14:39
For those who may suffer from this error,

 try 

` import 'brace/mode/json';`

since it looks like brace related error.

**Comment by josdejong** [comment] 2021-04-07 12:03
@cyrojyro I guess you're using an old version of `jsoneditor`, `brace` is not used anymore since `v7.1.0` (replaced with `ace-builds`).
