### ISSUE TITLE
What happens with copy/paste in Tree mode?

### ISSUE THREAD

**Issue by MarioMey** [josdejong/jsoneditor#208] opened 2015-07-10 14:36 UTC
There're problems to use them, uh?

**Comment by josdejong** [comment] 2015-07-10 15:10
What do you mean exactly? You can just copy/paste plain text in fields and values of the Tree mode.

**Comment by MarioMey** [comment] 2015-07-13 13:19
I swear that I was having problems with copy/paste... now, I just could use them.

Please, don't close this report, if it happens it to me again, I'll be back here.

**Comment by josdejong** [comment] 2015-07-13 14:02
Sure I will leave it open for a while, and once closed, you can always reopen it when needed, no worries.

**Comment by MarioMey** [comment] 2015-07-13 22:52
Ops, it happened again.

It can copy, but can't paste. I can paste text (copied in the Tree) in Code and Text modes... and, of course, outside the page. But not in Tree mode.

I don't know what more to say... it just doesn't work.

Firefox 39.0, Ubuntu 14.04 64x.

**Comment by josdejong** [comment] 2015-07-14 07:13
Thanks for the extra info. Can run FF 39 on Linux Mint here so that should be quite close to your system.

If I understand it correctly "after a while" you suddenly can't copy/paste in the Tree mode, and after refreshing the page it works again. Any clue on when the copy/paste functionality stops working? Is it after loading some document, or after some specific editing actions?

**Comment by MarioMey** [comment] 2015-07-14 12:49
It happens after saving.

I use a modified version of 04_load_and_save.html, but I tested it with the original and it happens with that file, too.

**Comment by josdejong** [comment] 2015-07-14 20:29
Ah, thanks, I can reproduce this.

Looks like a bug in Firefox: https://bugzilla.mozilla.org/show_bug.cgi?id=991537
The bug is known for more than a year now but nobody is working on it :(. I don't know if there is a workaround for it.

**Comment by MarioMey** [comment] 2015-07-14 20:32
Wow.

**Comment by josdejong** [comment] 2015-12-21 12:54
Since I can't really do anything to resolve this, I will close this issue now

**Closed by josdejong** 2015-12-21 12:54 UTC
