### ISSUE TITLE
Check box in tree 

### ISSUE THREAD

**Issue by Turgeson** [josdejong/jsoneditor#249] opened 2015-12-24 16:16 UTC
Is there a way to get a checkbox displayed for booleans in tree mode?  I've been using this a lot with a testing application and having the ability to toggle items would make an already great app better.

![booleancheckbox](https://cloud.githubusercontent.com/assets/398336/11996385/45932102-aa27-11e5-859f-74664b53d7a6.jpg)

**Comment by josdejong** [comment] 2015-12-31 12:51
Thanks for your suggestion @Turgeson, I think this is a duplicate of #193, lets continue any discussion there.

**Closed by josdejong** 2015-12-31 12:51 UTC

**Comment by Turgeson** [comment] 2015-12-31 20:02
I figures there was something like that. It would be a cool feature.

**Comment by josdejong** [comment] 2016-01-14 20:34
@Turgeson this feature is now available in v5.1.0

**Comment by Turgeson** [comment] 2016-01-14 20:39
Excellent!
