### ISSUE TITLE
If I have multiple json records, how can I obtain a json record being modified

### ISSUE THREAD

**Issue by MichaelPanwenjie** [josdejong/jsoneditor#1469] opened 2022-09-14 06:50 UTC
If I have multiple json records, how can I obtain a json record being modified
![image](https://user-images.githubusercontent.com/34026313/190081612-b16d9ab7-b031-4e7d-ac1d-d58a17ec12ed.png)

How to get the record in blue？ Many thanks！

**Comment by josdejong** [comment] 2022-09-16 11:38
I think this is a duplicate of #1459, please continue any discussion there.

**Closed by josdejong** 2022-09-16 11:38 UTC
