### ISSUE TITLE
svg is a absolute path in jsoneditor.css in dist floder

### ISSUE THREAD

**Issue by ChenSimin0103** [josdejong/jsoneditor#799] opened 2019-09-23 09:53 UTC
hi ,
I run `yarn add jsoneditor` to install jsoneditor to my react project  today , the version is 7.0.4
but when I import css file , It can't resolve 'img/jsoneditor-icons.svg' path from 'jsoneditor.css'
![image](https://user-images.githubusercontent.com/30794919/65416212-f495e380-de29-11e9-9b7f-7436d410ad79.png)

source code in Tag 7.0.4 is relative path ,althogh I can't find dist folder

**Comment by josdejong** [comment] 2019-09-23 17:48
Thanks for reporting, I think this is a duplicate of #675, let's continue any discussion there ok?

**Closed by josdejong** 2019-09-23 17:48 UTC
Labels: duplicate
